# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Citizen's Climate Lobby Panamá"
theme = ""

# Define the number of posts per page
paginate = 10

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		logo = "logo.png"
		brand = "Ciudadanos por un clima vivible"

		[[params.navigation.main]]
			name = "NOSOTROS"
			url = "/#about"

		[[params.navigation.main]]
			name = "VOLUNTARIOS"
			url = "/#about"

		[[params.navigation.main]]
			name = "TARIFAS DE CARBONO"
			url = "/#about"

		[[params.navigation.secundary]]
			name = "INGLÉS"
			url = "/#about"
		
		[[params.navigation.secundary]]
			name = "SITIO OFICIAL"
			url = "/#about"
		
		[[params.navigation.secundary]]
			name = "ÚNETE"
			url = "/#about"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Existimos para crear la voluntad política para un clima estable, por empoderar a individuos a tener grandes avances en el ejercicio de su poder político y personal."
		buttonText = "Únete"


	# About section
	[params.about]
		description = """\
					  Somos Ciudadanos por un Clima Vivible, el capítulo panameño de Citizens Climate Lobby. CCL es \
					  una organización internacional donde hacemos lo necesario para apoyar a nuestras autoridades \
					  electas para que puedan tomar acciones efectivas para solucionar la crisis climática. Más que todo, \
					  necesitan saber que las personas están de acuerdo: Necesitan el respaldo de sus electores. \
					  Todo lo que hacemos es con gratitud y respecto, nuestra única regla. ¡Les agradezco unirse a CCL y \
					  ser parte de la solución!"""

	# Testimony section
	[params.testimonials]
		headline = "LO QUE OTROS OPINAN"
		img1 = "quotes1.png"
		img2 = "quotes2.png" 
	
	[params.video]
		link = "https://www.youtube.com/embed/uGQnqojqhN0?html5=1"

	[params.socials]
		headline = "NUESTRAS REDES SOCIALES"
		twitterLink = "https://twitter.com/CCLPanamaCity"
		twitterAccount = "CCLPanamaCity"
		facebookLink = "https://www.facebook.com/CCLPanamaCity"
		facebookAccount = "Ciudadanos por un Clima Vivible - CCL Panamá"

	# Navigation Footer
	[[params.footer.nav]]
		name = "Nosotros"
		url = "/#about"
	
	[[params.footer.nav]]
		name = "Voluntarios"
		url = "/#about"

	[[params.footer.nav]]
		name = "Tarifas de carbono"
		url = "/#about"

	[[params.footer.nav]]
		name = "Versión Inglés"
		url = "/#about"
	
	[[params.footer.nav]]
		name = "Sitio oficial"
		url = "/#about"
	
	[[params.footer.nav]]
		name = "Únete"
		url = "/#about"